routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middlewareGroups' => ['web']], function(){
    // Authentication Routes
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
    Route::get('logoff', ['as' => 'logoff', 'uses' => 'Auth\LoginController@logout']);

    //                                              Register Routes                                            //
    /***********************************************************************************************************
    Route::get('registrar', ['as' => 'registrar', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
    Route::post('registrar', ['as' => 'registrar', 'uses' => 'Auth\RegisterController@register']);
    Route::get('registrar/verify/{confirmationCode}', [
         'as' => 'confirmation_path'
        ,'uses' => 'Auth\RegisterController@confirm' ]);
    ***********************************************************************************************************/
    // Resources with resources
    Route::resource('recursos', 'ResourcesCtrl', ['except' => ['show', 'create']]);
    // Tasks with resources
    Route::resource('tareas', 'TasksCtrl', ['except' => 'create']);
        // Tasks other
        Route::get('tareas/estado/{estat?}',[ 'as' => 'tareas.estado', 'uses' => 'TasksCtrl@filtrado']); // Filtrado selectivo
        //Route::get('estatUpdate/{tasca}/{estat}', 'TasksCtrl@estatUpdate'); // Updatea solo el estat
        Route::post('estatUpdate', 'TasksCtrl@estatUpdate'); // Updatea solo el estat
        Route::post('titleChangeDev', 'TasksCtrl@titleChange'); // Prueba de ajax
    // Revisions with resources
    Route::resource('revisiones', 'RevisionsCtrl', ['index', 'create']);
    // SysTasks with Resources
    Route::resource('sys_tareas', 'SysTasksCtrl', ['except' => 'create']);
        // SysTasks other
        Route::get('sys_tareas/estado/{estat?}',[ 'as' => 'sys_tareas.estado', 'uses' => 'SysTasksCtrl@filtrado']); // Filtrado selectivo
        Route::post('titleChangeSys', 'SysTasksCtrl@titleChange'); // Prueba de ajax
        Route::post('estatUpdateSys','SysTasksCtrl@estatUpdate');


    // Worked Hours With Resources
    Route::resource('horas', 'WorkedHoursCtrl', ['except' => 'create']);
        Route::get('horas/{month_year?}/index/', ['as' => 'horas.index', 'uses' => 'WorkedHoursCtrl@index']);
        Route::get('horas/{month_year?}/auto/', ['as' => 'horas.auto', 'uses' => 'WorkedHoursCtrl@autoCreate']);
    // Paginas one-page
    Route::get('/', 'PagsCtrl@getIndex');
});

resources/views/back/res/create.blade.php
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="recursoModalLabel">Nuevo recurso</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {!! Form::open(['route' => 'recursos.store', 'files' => 'true']) !!}
    <div class="modal-body">
      <div class="form-group">
        {{ Form::label('nombre', 'Nombre') }}
        {{ Form::text('nombre', null, ['class' => 'form-control']) }}  
      </div>
      <div class="form-group">
        {{ Form::label('url', 'URL') }}
        {{ Form::text('url', null, ['class' => 'form-control']) }}
      </div>
      <div class="form-group">
        <label class="custom-control custom-checkbox">
          {{ Form::checkbox('interno', 'true', true, ['class' => 'custom-control-input']) }}
          <span class="custom-control-indicator"></span>
          <span class="custom-control-description">Abrir en pestaña</span>
        </label>
      </div>
      <div class="form-group">
        <label class="btn btn-outline-primary btn-file col-5">
          <span class="text-center">Seleccionar imagen...</span>
          {{ Form:: file('iconImg') }}
        </label>
        <span id="filename"></span>
      </div>
      <div class="form-group">
        
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cerrar</button>
      {{ Form::submit('Guardar', ['class' => 'btn btn-outline-dark btn-block']) }}  
    </div>
    {{ Form::close() }}
  </div>
</div>  

resources/views/back/res/edit.blade.php
@extends('_templates.main')

@section('title', 'Recursos')

@section('stylesheets')
  {{ Html::style(asset('css/index.css')) }}
@endsection

@section('jumbotron')
  <div class="jumbotron jumbotron top-spacing-20">
    <div class="container">
      <h1 class="display-5 text-center">
        Editar <em>{{ $re->nombre }}</em>
      </h1>
      <hr />
      <p class="lead row justify-content-between">
        <a href="{{ URL::previous() }}" class="btn btn-secondary col-1"><span class="fa fa-arrow-left fa-lg"></span></a>
      </p>
    </div>
  </div>
@endsection
@section('content')
  <div class="col-12 row justify-content-between">
    <div class="col-8">
      {{ Form::model($re,['route' => ['recursos.update', $re->id], 'files' => 'true', 'method' => 'PUT']) }}
      <div class="form-group">
        {{ Form::label('nombre', 'Nombre') }}
        {{ Form::text('nombre', null, ['class' => 'form-control']) }}
      </div>
      <div class="form-group">
        {{ Form::label('url', 'URL') }}
        {{ Form::text('url', null, ['class' => 'form-control']) }}
      </div>
      <div class="form-group">
        <label class="custom-control custom-checkbox">
          {{ Form::checkbox('interno', 'true',$re->interno == 0 ? true : false, ['class' => 'custom-control-input']) }}
          <span class="custom-control-indicator"></span>
          <span class="custom-control-description">Abrir en pestaña</span>
        </label>
      </div>
      <div class="form-group">
        <label class="btn btn-outline-primary btn-file col-3">
          <span class="text-center">Seleccionar imagen...</span>
          {{ Form:: file('iconImg') }}
        </label>
        <span id="filename"><i class="fa fa-file-image-o"></i> {{ $re->icono == 'default' ? 'Ninguno' : $re->icono }}</span>
        @if($re->icono != 'default')
        <div>
          <label class="custom-control custom-checkbox">
            {{ Form::checkbox('del_img', 'true', null, ['class' => 'custom-control-input']) }}
            <span class="custom-control-indicator"></span>
            <span class="custom-control-description">Eliminar imagen</span>
          </label>
        </div>
        @endif
      </div>
      <div class="form-group">
        {{ Form::submit('Guardar', ['class' => 'btn btn-outline-dark btn-block']) }}
      </div>
      {{ Form::close() }}
    </div>
    <div class="col-2 ml-auto">
      <ul class="nav flex-column text-left bottom-spacing-30">
            <h5 class="text-center">
              Información
            </h5>
            <li class="nav-item">
              <span class="fa fa-calendar"></span> Creado
            </li>
            <li class="nav-item">
              {{ Date::parse($re->created_at)->format('d/m/Y') }}
              {{ Date::parse($re->created_at)->format('H:i') }}
            </li>
            <hr />
            <li class="nav-item">
              <span class="fa fa-calendar"></span> Modificado
            </li>
            <li class="nav-item">
              {{ Date::parse($re->updated_at)->format('d/m/Y') }}
              {{ Date::parse($re->updated_at)->format('H:i') }}
            </li>
            <hr />
            {{ Form::open(['route' => ['recursos.destroy', $re->id], 'method' => 'DELETE']) }}
              {{ Form::submit('Borrar', ['class' => 'btn btn-outline-danger btn-block']) }}
            {{ Form::close() }}
          </ul>
    </div>
  </div>
@endsection

@section('scripts')
  <script>
    $(document).on('change',':file', function(){
      $(this).parent().removeClass('btn-outline-primary');
      $(this).parent().addClass('btn-outline-success');
      $imgName = $(this).val().substring($(this).val().lastIndexOf("\\") + 1, $(this).val().length);
      $(this).parent().children('span').text('Imagen cargada');
      $("#filename").html(' <i class="fa fa-file-image-o"></i> ' + $imgName);
    });
  </script>
@endsection

resources/views/back/res/index.blade.php
@extends('_templates.main')

@section('title', 'Recursos')

@section('stylesheets')
    {{ Html::style(asset('css/index.css')) }}
@endsection

@section('jumbotron')
  <div class="jumbotron jumbotron top-spacing-20">
    <div class="container">
      <h1 class="display-5 text-center">
        Recursos
      </h1>
      <hr />
      <p class="lead row justify-content-between">
        <a href="{{ URL::previous() }}" class="btn btn-secondary col-1"><span class="fa fa-arrow-left fa-lg"></span></a>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-secondary col-1" data-toggle="modal" data-target="#recursoModal"><span class="fa fa-plus fa-lg"></span></button>
      </p>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="recursoModal" tabindex="-1" role="dialog" aria-labelledby="recursoModalLabel" aria-hidden="true">
    @include('back/res/create')
  </div>
@endsection

@section('content')
  <table class="table table-sm table-hover table-bordered">
    <thead class="thead-dark">
      <tr>
        <th class="text-center">Nombre</th>
        <th class="text-center">URL</th>
        <th class="text-center">Ventana</th>
        <th class="text-center">Imagen</th>
        <th class="text-center">Acciones</th>
      </tr>
    </thead>
    <tbody>
      @foreach($res as $i => $resource)
      <tr>
        <td>{{ $resource->nombre }}</td>
        <td>{{ Html::link($resource->url, 'Enlace', ['class' => 'btn btn-link']) }}</td>
        <td class="text-center"><span class="fa fa-{{ $resource->interno == 1 ? 'check-square-o' : 'square-o'  }}"></span> </td>
        <td class="text-center"><img src="{{ $resource->icono == 'default' ? asset('logos/favicon.png') : asset('images/'.$resource->icono) }}" alt="{{ $resource->nombre }}" style="border-radius: 50%" height="50" width="50" /></td>
        <td class="text-center"><a href="{{ route('recursos.edit', $resource->id) }}"><span class="fa fa-pencil fa-lg"></span></a></td>
      </tr>
      @endforeach
    </tbody>
  </table>
@endsection

@section('scripts')
  <script>
    $(document).on('change',':file', function(){
      $(this).parent().removeClass('btn-outline-primary');
      $(this).parent().addClass('btn-outline-success');
      $imgName = $(this).val().substring($(this).val().lastIndexOf("\\") + 1, $(this).val().length);
      $(this).parent().children('span').text('Imagen cargada');
      $("#filename").html(' <i class="fa fa-file-image-o"></i> ' + $imgName);
    });
  </script>
@endsection