routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middlewareGroups' => ['web']], function(){
    // Authentication Routes
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
    Route::get('logoff', ['as' => 'logoff', 'uses' => 'Auth\LoginController@logout']);

    //                                              Register Routes                                            //
    /***********************************************************************************************************
    Route::get('registrar', ['as' => 'registrar', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
    Route::post('registrar', ['as' => 'registrar', 'uses' => 'Auth\RegisterController@register']);
    Route::get('registrar/verify/{confirmationCode}', [
         'as' => 'confirmation_path'
        ,'uses' => 'Auth\RegisterController@confirm' ]);
    ***********************************************************************************************************/
    // Resources with resources
    Route::resource('recursos', 'ResourcesCtrl', ['except' => ['show', 'create']]);
    // Tasks with resources
    Route::resource('tareas', 'TasksCtrl', ['except' => 'create']);
        // Tasks other
        Route::get('tareas/estado/{estat?}',[ 'as' => 'tareas.estado', 'uses' => 'TasksCtrl@filtrado']); // Filtrado selectivo
        //Route::get('estatUpdate/{tasca}/{estat}', 'TasksCtrl@estatUpdate'); // Updatea solo el estat
        Route::post('estatUpdate', 'TasksCtrl@estatUpdate'); // Updatea solo el estat
        Route::post('titleChangeDev', 'TasksCtrl@titleChange'); // Prueba de ajax
    // Revisions with resources
    Route::resource('revisiones', 'RevisionsCtrl', ['index', 'create']);
    // SysTasks with Resources
    Route::resource('sys_tareas', 'SysTasksCtrl', ['except' => 'create']);
        // SysTasks other
        Route::get('sys_tareas/estado/{estat?}',[ 'as' => 'sys_tareas.estado', 'uses' => 'SysTasksCtrl@filtrado']); // Filtrado selectivo
        Route::post('titleChangeSys', 'SysTasksCtrl@titleChange'); // Prueba de ajax
        Route::post('estatUpdateSys','SysTasksCtrl@estatUpdate');


    // Worked Hours With Resources
    Route::resource('horas', 'WorkedHoursCtrl', ['except' => 'create']);
        Route::get('horas/{month_year?}/index/', ['as' => 'horas.index', 'uses' => 'WorkedHoursCtrl@index']);
        Route::get('horas/{month_year?}/auto/', ['as' => 'horas.auto', 'uses' => 'WorkedHoursCtrl@autoCreate']);
    // Paginas one-page
    Route::get('/', 'PagsCtrl@getIndex');
});

resources/views/back/rev/create.blade.php
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="revisionesModalLabel">Nuevo cambio</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
      <div class="modal-body text-left">
      {!! Form::open(['route' => 'revisiones.store', 'class' => 'col-12']) !!}
        @if($table == "dev")
          {{ Form::hidden('task_id', $t->id) }}
        @elseif($table == "sys")
          {{ Form::hidden('sys_task_id', $t->id) }}
        @endif
        {{ Form::hidden('autor_id', Auth::user()->id) }}
        <div class="form-inline col-12">
          <div class="form-group">
            {{ Form::label('num_rev', 'Numero de revisión') }}
            {{ Form::number('num_rev', $r, ['class' => 'form-control col-12']) }}
          </div>
          @if($table == "dev")
            <div class="form-group left-spacing-50">
              {{ Form::label('hash', 'Hash') }}
              {{ Form::text('hash', null, ['class' => 'form-control col-12']) }}
            </div>
          @endif
        </div>
        <div class="form-group col-12">
          {{ Form::label('desc','Descripcion') }}
          {{ Form::textarea('desc', null,['class' => 'form-control']) }}
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cerrar</button>
        {{ Form::submit('Guardar', ['class' => 'btn btn-outline-dark btn-block']) }}  
      </div>
      {{ Form::close() }}
    </div>
  </div>
</div>

resources/views/back/rev/edit.blade.php
@extends('_templates.main')

@section('title', 'Cambios')

@section('stylesheets')
    {{ Html::style(asset('css/tareas/index.css')) }}
    {{ Html::style('http://cdn.dxcodercrew.net/select2/dist/css/select2.css') }}
    <script src="http://cdn.dxcodercrew.net/tinymce/tinymce.min.js"></script>

    <script type="text/javascript">
    tinymce.init({
        selector: 'textarea'
        ,language: 'es'
        ,plugins: [
            "advlist autolink autosave link image lists charmap print preview hr anchor pagebreak code"
        ]
        ,height: 200
        ,max_height: 200
        ,min_height: 200
        ,branding: false
    });
    </script>
@endsection

@section('jumbotron')
  <div class="jumbotron jumbotron top-spacing-20">
    <div class="container">
      <h1 class="display-5 text-center">
       Editar cambio
      </h1>
      <hr />
      <p class="lead row justify-content-between">
        <a href="{{ URL::previous() }}" class="btn btn-secondary col-1"><span class="fa fa-arrow-left fa-lg"></span></a>
      </p>
    </div>
  </div>
@endsection

@section('content')
<div class="col-12 row justify-content-between">
  <div class="col-10 row justify-content-start">
    {{ Form::model($rev, ['route' =>['revisiones.update', $rev->id],'files' => 'false', 'method' => 'PUT', 'class' => 'col-12']) }}
      {{ Form::hidden('task_id', $rev->task_id) }}
      {{ Form::hidden('autor_id', Auth::user()->id) }}
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">
            <span class="btn btn-success circle fa fa-pencil"></span>

          </h4>
          <h6 class="card-subtitle mb-2 text-muted"></h6>
        </div>
        <div class="card-body">
          <div class="card-text row">
            <div class="form-group col-4">
              {{ Form::label('num_rev', 'Numero de revisión') }}
              {{ Form::number('num_rev', null, ['class' => 'form-control']) }}  
            </div>
            <div class="form-group col-4">
              {{ Form::label('hash', 'Hash') }}
              {{ Form::text('hash', null, ['class' => 'form-control']) }}  
            </div>
            <div class="form-group col-12">
              {{ Form::label('desc','Descripcion') }}
              {{ Form::textarea('desc', null,['class' => 'form-control']) }}
            </div>
          </div>
        </div>
        <div class="card-footer">
          {{ Form::submit('Guardar', ['class' => 'btn btn-outline-dark btn-block']) }}
        </div>
      </div>
    {{ Form::close() }}
  </div>
  <div class="col ml-auto">
    <div class="card">
      <div class="card-body">
        <h5>Información</h5>
        <ul class="nav flex-column text-left">
          <li class="nav-item">
            <span class="fa fa-calendar"></span> Creado
          </li>
          <li class="nav-item">
            {{ Date::parse($rev->created_at)->format('d/m/Y') }}
            {{ Date::parse($rev->created_at)->format('H:i') }}
          </li>
          <hr />
          <li class="nav-item">
            <span class="fa fa-calendar"></span> Modificado
          </li>
          <li class="nav-item">
            {{ Date::parse($rev->updated_at)->format('d/m/Y') }}
            {{ Date::parse($rev->updated_at)->format('H:i') }}
          </li>
          <li class="nav-item">
            <span class="fa fa-user"></span> Por:
          </li>
          <li class="nav-item">
            {{ $rev->user->name }}
          </li>
        </ul>
      </div>
      {{ Form::open(['route' => ['revisiones.destroy', $rev->id], 'method' => 'DELETE']) }}
        {{ Form::submit('Eliminar', ['class' => 'btn btn-outline-danger btn-block']) }}
      {{ Form::close() }}
    </div>
      
  </div>
</div>
@endsection

resources/views/back/rev/show.blade.php
@extends('_templates.main')

@section('title', 'Cambios')

@section('stylesheets')
    {{ Html::style(asset('css/revisiones/index.css')) }}   
@endsection

@section('jumbotron')
  <div class="jumbotron jumbotron top-spacing-20">
    <div class="container">
      <h1 class="display-5 text-center">
       Ver cambio
      </h1>
      <hr />
      <p class="lead row justify-content-between">
        <a href="{{ URL::previous() }}" class="btn btn-secondary col-1"><span class="fa fa-arrow-left fa-lg"></span></a>
      </p>
    </div>
  </div>
@endsection

@section('content')
<div class="col-12 row justify-content-between">
  <div class="col-10 row justify-content-between">
    <div class="col-12">
      <div class="card">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title"><span class="btn btn-secondary circle fa fa-info"></span> Revisión {{ $rev->num_rev }}</h4>
            <h6 class="card-subtitle mb-2 text-muted">{{ $rev->hash === null ? 'Sin hash' : 'Hash: '.$rev->hash }}</h6>
          </div>
          <div class="card-body">
            <div class="card-text">
              {!! $rev->desc !!}
            </div>
          </div>
          <div class="card-footer">
            
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col ml-auto">
    <div class="card">
      <div class="card-body">
        <h5>Información</h5>
        <ul class="nav flex-column text-left">
          <li class="nav-item">
            <span class="fa fa-calendar"></span> Creado
          </li>
          <li class="nav-item">
            {{ Date::parse($rev->created_at)->format('d/m/Y') }}
            {{ Date::parse($rev->created_at)->format('H:i') }}
          </li>
          <hr />
          <li class="nav-item">
            <span class="fa fa-calendar"></span> Modificado
          </li>
          <li class="nav-item">
            {{ Date::parse($rev->updated_at)->format('d/m/Y') }}
            {{ Date::parse($rev->updated_at)->format('H:i') }}
          </li>
          <li class="nav-item">
            <span class="fa fa-user"></span> Por:
          </li>
          <li class="nav-item">
            {{ $rev->user->name }}
          </li>
        </ul>
      </div>
      <a href="{{ route('revisiones.edit', $rev->id) }}" class="btn btn-outline-primary btn-block"><span class="fa fa-pencil"></span> Editar</a>
    </div>
      
  </div>
</div>
@endsection