routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middlewareGroups' => ['web']], function(){
    // Authentication Routes
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
    Route::get('logoff', ['as' => 'logoff', 'uses' => 'Auth\LoginController@logout']);

    //                                              Register Routes                                            //
    /***********************************************************************************************************
    Route::get('registrar', ['as' => 'registrar', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
    Route::post('registrar', ['as' => 'registrar', 'uses' => 'Auth\RegisterController@register']);
    Route::get('registrar/verify/{confirmationCode}', [
         'as' => 'confirmation_path'
        ,'uses' => 'Auth\RegisterController@confirm' ]);
    ***********************************************************************************************************/
    // Resources with resources
    Route::resource('recursos', 'ResourcesCtrl', ['except' => ['show', 'create']]);
    // Tasks with resources
    Route::resource('tareas', 'TasksCtrl', ['except' => 'create']);
        // Tasks other
        Route::get('tareas/estado/{estat?}',[ 'as' => 'tareas.estado', 'uses' => 'TasksCtrl@filtrado']); // Filtrado selectivo
        //Route::get('estatUpdate/{tasca}/{estat}', 'TasksCtrl@estatUpdate'); // Updatea solo el estat
        Route::post('estatUpdate', 'TasksCtrl@estatUpdate'); // Updatea solo el estat
        Route::post('titleChangeDev', 'TasksCtrl@titleChange'); // Prueba de ajax
    // Revisions with resources
    Route::resource('revisiones', 'RevisionsCtrl', ['index', 'create']);
    // SysTasks with Resources
    Route::resource('sys_tareas', 'SysTasksCtrl', ['except' => 'create']);
        // SysTasks other
        Route::get('sys_tareas/estado/{estat?}',[ 'as' => 'sys_tareas.estado', 'uses' => 'SysTasksCtrl@filtrado']); // Filtrado selectivo
        Route::post('titleChangeSys', 'SysTasksCtrl@titleChange'); // Prueba de ajax
        Route::post('estatUpdateSys','SysTasksCtrl@estatUpdate');


    // Worked Hours With Resources
    Route::resource('horas', 'WorkedHoursCtrl', ['except' => 'create']);
        Route::get('horas/{month_year?}/index/', ['as' => 'horas.index', 'uses' => 'WorkedHoursCtrl@index']);
        Route::get('horas/{month_year?}/auto/', ['as' => 'horas.auto', 'uses' => 'WorkedHoursCtrl@autoCreate']);
    // Paginas one-page
    Route::get('/', 'PagsCtrl@getIndex');
});

resources/views/back/tareas/create.blade.php
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="tareaModalLabel">Nueva tarea</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
      <div class="modal-body">
      {!! Form::open(['route' => 'tareas.store']) !!}
        <div class="form-inline">
          <div class="form-group">
            {{ Form::label('glpi_id', 'GLPI') }}
            {{ Form::number('glpi_id', null, ['class' => 'form-control col-md-12']) }}  
          </div>
          <div class="form-group left-spacing-50">
            {{ Form::label('redmine_id', 'Redmine') }}
            {{ Form::number('redmine_id', null, ['class' => 'form-control col-md-12']) }}  
          </div>
        </div>
        <div class="form-group">
          {{ Form::label('redmine_t', 'Tipo') }}
          {{ Form::select('redmine_t', [null => 'Selecciona', '1' => 'Tarea', '2' => 'Error'], null, ['class' => 'custom-select col-4']) }}
        </div>
        <div class="form-group">
          {{ Form::label('project_name', 'Nombre Proyecto') }}
          {{ Form::text('project_name', null, ['class' => 'form-control']) }}
        </div>
        <div class="form-group">
          {{ Form::label('repo', 'Repositorio') }}
          {{ Form::text('repo', null, ['class' => 'form-control col-8']) }}
        </div>
        <div class="form-group">
          {{ Form::label('desc','Descripcion') }}
          {{ Form::textarea('desc', null,['class' => 'form-control']) }}
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cerrar</button>
        {{ Form::submit('Guardar', ['class' => 'btn btn-outline-dark btn-block']) }}  
      </div>
      {{ Form::close() }}
    </div>
  </div>
</div>

resources/views/back/tareas/edit.blade.php
@extends('_templates.main')

@section('title', 'Tareas')

@section('stylesheets')
    {{ Html::style(asset('css/tareas/index.css')) }}
    {{ Html::style('http://cdn.dxcodercrew.net/select2/dist/css/select2.css') }}
    <script src="http://cdn.dxcodercrew.net/tinymce/tinymce.min.js"></script>

    <script type="text/javascript">
    tinymce.init({
        selector: 'textarea'
        ,language: 'es'
        ,plugins: [
            "advlist autolink autosave link image lists charmap print preview hr anchor pagebreak code"
        ]
        ,height: 200
        ,max_height: 200
        ,min_height: 200
        ,branding: false
    });
      
    function delProjName(ele){
        ele.removeAttribute('readonly');
        ele.addEventListener('blur', function(e,ele){
          var newName = $("#project_name").val();
          var taskId = $("#task_id").val();

          $.ajax({
            type: 'POST',
            url: '/titleChangeDev',
            data: { tarea:taskId, projectName:newName, _token: "{{ csrf_token() }}"},
            success: function (data) {
              location.reload();
            },
            error: function(data){
              alert(JSON.stringify(data));
            }
          });
      });
    }
          
    function updateStat(){
      var taskId = $("#task_id").val();
      var estatCod = $("#estat").val();
      
      $.ajax({
         type:'POST',
         url:'/estatUpdate',
        data: { 
          tasca: taskId, 
          estat: estatCod, 
          _token: "{{ csrf_token() }}"
        },
        success: function (data) {
          location.reload();
        },
        error: function(data){
          alert(JSON.stringify(data));
        }
      });
    }
    </script>
@endsection

@section('jumbotron')
    @if($t->estat == 0)
      <div class="jumbotron jumbotron top-spacing-20 bg-light">
    @elseif($t->estat == 1)
      <div class="jumbotron jumbotron top-spacing-20 bg-warning">
    @elseif($t->estat == 2)
      <div class="jumbotron jumbotron top-spacing-20 bg-success">
    @elseif($t->estat == 3)
      <div class="jumbotron jumbotron top-spacing-20 bg-danger">
    @else
      <div class="jumbotron jumbotron top-spacing-20 bg-info">
    @endif
    <div class="container">
      <h1 class="display-5 text-center">
       Editar tarea
      </h1>
    </div>
  </div>
@endsection

@section('content')
<div class="col-12 row justify-content-between">
  <div class="col-12 bottom-spacing-10">
    <a href="/tareas/{{ $t->id }}" class="btn btn-sm circle-sm btn-secondary col-1"><span class="fa fa-arrow-left fa-sm"></span></a>
  </div>
  <div class="col-10 row justify-content-start">
    {{ Form::model($t, ['route' =>['tareas.update', $t->id],'files' => 'false', 'method' => 'PUT', 'class' => 'col-12']) }}
      {{ csrf_field() }}
      @if($t->estat == 0)
        <div class="card border-light">
      @elseif($t->estat == 1)
        <div class="card border-warning">
      @elseif($t->estat == 2)
        <div class="card border-success">
      @elseif($t->estat == 3)
        <div class="card border-danger">
      @else
        <div class="card border-info">
      @endif
        <div class="card-header">
          <h4 class="card-title">
            <span class="btn btn-success circle fa fa-pencil ml-auto"></span>
          </h4>
          <h6 class="card-subtitle mb-2 text-muted"></h6>
        </div>
        <div class="card-body">
          <div class="card-text row">
            <div class="form-group col-12">
              {{ Form::hidden('task_id', $t->id, ['id' => 'task_id']) }}
              {{ Form::label('project_name', 'Nombre Proyecto') }}
              @if($t->project_name != '' || $t->project_name != null)
                {{ Form::text('project_name', null, ['class' => 'form-control','readonly', 'ondblclick' => 'delProjName(this)']) }}
              @else
                {{ Form::text('project_name', null, ['class' => 'form-control', 'onclick' => 'delProjName(this)']) }}
              @endif
            </div>
            <div class="form-group col-4">
              {{ Form::label('glpi_id', 'GLPI') }}
              {{ Form::number('glpi_id', null, ['class' => 'form-control']) }}  
            </div>
            <div class="form-group col-4">
              {{ Form::label('redmine_id', 'Redmine') }}
              {{ Form::number('redmine_id', null, ['class' => 'form-control']) }}  
            </div>
            <div class="form-group col-4">
              {{ Form::label('redmine_t', 'Tipo') }}
              {{ Form::select('redmine_t', [null => 'Selecciona', '1' => 'Tarea', '2' => 'Error'], null, ['class' => 'form-control custom-select']) }} 
            </div>
            <div class="form-group col-8">
              {{ Form::label('repo', 'Repositorio') }}
              {{ Form::text('repo', null, ['class' => 'form-control']) }}
            </div>
            <div class="form-group col-4">
              {{ Form::label('estat', 'Estado') }}
              {{ Form::select('estat', [null => 'Selecciona', '0' => 'Nuevo/En espera', '1' => 'En curso', '2' => 'Finalizado', '3' => 'Cancelado'], null, ['class' => 'form-control custom-select', 'onchange' => 'updateStat()']) }} 
            </div>
            <div class="form-group col-12">
              {{ Form::label('desc','Descripcion') }}
              {{ Form::textarea('desc', null,['class' => 'form-control']) }}
            </div>
          </div>
        </div>
        <div class="card-footer">
          {{ Form::submit('Guardar', ['class' => 'btn btn-outline-dark btn-block']) }}
        </div>
      </div>
    {{ Form::close() }}
  </div>
  <div class="col ml-auto">
    <div class="card">
      <div class="card-body">
        <h5>Información</h5>
        <ul class="nav flex-column text-left">
          <li class="nav-item">
            <span class="fa fa-calendar"></span> Creado
          </li>
          <li class="nav-item">
            {{ Date::parse($t->created_at)->format('d/m/Y') }}
            {{ Date::parse($t->created_at)->format('H:i') }}
          </li>
          <hr />
          <li class="nav-item">
            <span class="fa fa-calendar"></span> Modificado
          </li>
          <li class="nav-item">
            {{ Date::parse($t->updated_at)->format('d/m/Y') }}
            {{ Date::parse($t->updated_at)->format('H:i') }}
          </li>
        </ul>
      </div>
      {{ Form::open(['route' => ['tareas.destroy', $t->id], 'method' => 'DELETE']) }}
        {{ Form::submit('Eliminar', ['class' => 'btn btn-outline-danger btn-block']) }}
      {{ Form::close() }}
    </div>
      
  </div>
</div>
@endsection

resources/views/back/tareas/index.blade.php
@extends('_templates.main')

@section('title', 'Tareas')

@section('stylesheets')
    {{ Html::style(asset('css/tareas/index.css')) }}
    {{ Html::style('http://cdn.dxcodercrew.net/select2/dist/css/select2.css') }}
    <script src="http://cdn.dxcodercrew.net/tinymce/tinymce.min.js"></script>

    <script type="text/javascript">
    tinymce.init({
        selector: 'textarea'
        ,language: 'es'
        ,plugins: [
            "advlist autolink autosave link image lists charmap print preview hr anchor pagebreak code"
        ]
        ,height: 200
        ,max_height: 200
        ,min_height: 200
        ,branding: false
    });
    </script>
@endsection

@section('jumbotron')
  <div class="jumbotron jumbotron top-spacing-20">
    <div class="container">
      <h1 class="display-5 text-center">
        Tareas
      </h1>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="tareaModal" tabindex="-1" role="dialog" aria-labelledby="tareaModalLabel" aria-hidden="true">
    @include('back/tareas/create')
  </div>
@endsection

@section('content')
  <div class="col-12 row justify-content-center">
    <div class="col-12 row justify-content-between">
      <div class="btn-group-sm ml-auto" role="group">
        <button type="button" class="btn btn-default circle-sm" data-toggle="modal" data-target="#tareaModal"><span class="fa fa-plus fa-sm"></span></button>
        <button id="btnGroupDrop1" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Mostrar
        </button>
        <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
          <a class="dropdown-item" href="/tareas"><span class="badge badge-pill badge-primary">{{ ($tAll > 9 ? '' : '0') }}{{ $tAll }}</span>Todos</a>
          <a class="dropdown-item" href="/tareas/estado/0"><span class="badge badge-pill badge-secondary">{{ ($tNew > 9 ? '' : '0') }}{{ $tNew }}</span> Nuevos/En espera</a>
          <a class="dropdown-item" href="/tareas/estado/1"><span class="badge badge-pill badge-warning">{{ ($tCur > 9 ? '' : '0') }}{{ $tCur }}</span> En curso</a>
          <a class="dropdown-item" href="/tareas/estado/2"><span class="badge badge-pill badge-success">{{ ($tOk > 9 ? '' : '0') }}{{ $tOk }}</span> Finalizados</a>
          <a class="dropdown-item" href="/tareas/estado/3"><span class="badge badge-pill badge-danger">{{ ($tKo > 9 ? '' : '0') }}{{ $tKo }}</span> Cancelados</a>
        </div>
      </div>
    </div>
    <div class="row col-12 justify-content-center">
      {!! $ts->render('vendor.pagination.bootstrap-4') !!}
    </div>
    <div class="col-6">
      <div class="list-group col">
        @foreach($ts as $i => $t)
        <a href="{{ route('tareas.show',$t->id)}}" class="list-group-item list-group-item-action list-group-item-{{ $t->estat === null || $t->estat === 0 ? 'light' : ($t->estat === 1 ? 'warning' : ($t->estat ===2 ? 'success' : 'danger')) }}">
          <div class="row justify-content-between">
            <div class="col">
              @if($t->project_name != '' || $t->project_name != null)
                Proyecto: {{ $t->project_name }}
              @else
                @if($t->redmine_id === null && $t->glpi_id === null)
                  Tarea sin numero de GLPI o Redmine
                @else
                  @if($t->redmine_id !== null)
                    @if($t->glpi_id !== null)
                      @if($t->redmine_t !== '0')
                        {{ $t->redmine_t === '1' ? '[Tasca' : '[Error' }}:
                      @endif
                        #{{ $t->redmine_id }}][GLPI: #{{ $t->glpi_id }}]
                    @else
                      @if($t->redmine_t !== '0')
                        {{ $t->redmine_t === '1' ? '[Tasca' : '[Error' }}:
                      @endif
                         #{{ $t->redmine_id }}]
                    @endif
                  @else
                    [GLPI: #{{ $t->glpi_id }}]
                  @endif
                @endif
              @endif
            </div>
            <div class="col-1 text-right">
              <i class="fa fa-arrow-right"></i>
            </div>
          </div>
        </a>
        @endforeach
      </div>
    </div>
    <div class="row col-12 justify-content-center top-spacing-50">
        {!! $ts->render('vendor.pagination.bootstrap-4') !!}
    </div>
  </div>
@endsection

@section('scripts')
    {{ Html::script('http://cdn.dxcodercrew.net/select2/dist/js/select2.min.js') }}
    {{ Html::script('http://cdn.dxcodercrew.net/select2/dist/js/i18n/es.js') }}
    <script type="text/javascript">
        $('.select2-multi').select2({
            language: "es"
        });
    </script>
@endsection

resources/views/back/tareas/show.blade.php
@extends('_templates.main')

@section('title', 'Tareas')

@section('stylesheets')
    {{ Html::style(asset('css/tareas/index.css')) }}
    {{ Html::style('http://cdn.dxcodercrew.net/select2/dist/css/select2.css') }}
    <script src="http://cdn.dxcodercrew.net/tinymce/tinymce.min.js"></script>

    <script type="text/javascript">
    tinymce.init({
        selector: 'textarea'
        ,language: 'es'
        ,plugins: [
            "advlist autolink autosave link image lists charmap print preview hr anchor pagebreak code"
        ]
        ,height: 200
        ,max_height: 200
        ,min_height: 200
        ,branding: false
    });
    </script>
    
@endsection

@section('jumbotron')
    @if($t->estat == 0)
      <div class="jumbotron jumbotron top-spacing-20 bg-light">
    @elseif($t->estat == 1)
      <div class="jumbotron jumbotron top-spacing-20 bg-warning">
    @elseif($t->estat == 2)
      <div class="jumbotron jumbotron top-spacing-20 bg-success">
    @elseif($t->estat == 3)
      <div class="jumbotron jumbotron top-spacing-20 bg-danger">
    @else
      <div class="jumbotron jumbotron top-spacing-20 bg-info">
    @endif
    <div class="container">
      <h1 class="display-5 text-center">
       Ver tarea
      </h1>
    </div>
  </div>
@endsection

@section('content')
<div class="col-12 row justify-content-between">
  <div class="col-10 row justify-content-between">
    <div class="col-12 bottom-spacing-10">
      <a href="/tareas/estado/1" class="btn btn-sm circle-sm btn-secondary col-1"><span class="fa fa-arrow-left fa-sm"></span></a>
    </div>
    <div class="col-8"> 
        @if($t->estat == 0)
          <div class="card border-light">
        @elseif($t->estat == 1)
          <div class="card border-warning">
        @elseif($t->estat == 2)
          <div class="card border-success">
        @elseif($t->estat == 3)
          <div class="card border-danger">
        @else
          <div class="card border-info">
        @endif
          <div class="card-header">
            <h4 class="card-title"><span class="btn btn-secondary circle fa fa-info"></span> Descripción</h4>
            @if($t->project_name != '' || $t->project_name != null)
            <h5 class="card-subtitule mb-2">
              {{ $t->project_name }}
            </h5>
            @endif
            <h6 class="card-subtitle mb-2 text-muted">Estado: {{ $t->estat === null || $t->estat === 0 ? 'Nueva' : ($t->estat === 1 ? 'En curso' : ($t->estat === 2 ? 'Finalizado' : 'Cancelado')) }}</h6>
          </div>
          <div class="card-body">
            <p class="card-text">{!! $t->desc !!}</p>
          </div>
          <div class="card-footer">
            <div class="col-12 row justify-content-between">
              <div class="col-8">
                <h3>Cambios</h3>
              </div>
              <div class="col-4 text-right">
                <!-- Button trigger modal -->
                @if($t->estat !== 2)
                <button type="button" class="btn btn-light btn-sm circle" data-toggle="modal" data-target="#revisionesModal"><span class="fa fa-plus fa-lg"></span></button>
                @endif
                <!-- Modal -->
                <div class="modal fade" id="revisionesModal" tabindex="-1" role="dialog" aria-labelledby="revisionesModal" aria-hidden="true">
                  @include('back/rev/create')
                </div>
              </div>
            </div>
            <div class="row justify-content-center">
              <div class="list-group  col-8">
                @foreach($t->part_rev($t->id) as $i => $rev)
                  <a href="{{ route('revisiones.show', $rev->id) }}" class="list-group-item list-group-item-action {{ $i%2 == 0 ? 'list-group-item-light' : 'list-group-item-secondary'}}">
                    <div class="d-flex w-100 justify-content-between">
                      <h5 class="mb-1">Revisión {{ $rev->num_rev }}</h5>
                      <small>{{$rev->hash !== null ? '(Hash: '.$rev->hash : '(Sin hash' }})</small>
                    </div>
                    <div class="row justify-content-between">
                      <div class="col">
                        
                      </div>
                      <div class="col-1 text-right">
                        <i class="fa fa-arrow-right"></i>
                      </div>
                    </div>
                  </a>
                @endforeach
              </div>
            </div>
          </div>
        </div>
    </div>
    <div class="col-4">
      @if($t->estat == 0)
        <div class="card border-light">
      @elseif($t->estat == 1)
        <div class="card border-warning">
      @elseif($t->estat == 2)
        <div class="card border-success">
      @elseif($t->estat == 3)
        <div class="card border-danger">
      @else
        <div class="card border-info">
      @endif
        <div class="card-header">
          <h4 class="card-title"><span class="btn btn-secondary circle fa fa-link"></span> Enlaces</h4>
          <h6 class="card-subtitle mb-2 text-muted">
          </h6>
        </div>
        <div class="card-body">
          <p class="card-text">
            <div class="">
              {{ Form::label('glpi_id', 'GLPI:') }}
              @if($t->glpi_id === null)
                {{ Form::text('glpi_id', 'Sin numero de GLPI', ['class' => 'form-control-plaintext', 'readonly']) }}
              @else
                {{ Html::link('http://glpi.mgc.es/front/ticket.form.php?id='.$t->glpi_id, $t->glpi_id, ['class' => 'btn btn-link', 'target' => '_blank']) }}
              @endif
            </div>
            <div class="">
              {{ Form::label('redmine_id', 'Redmine:') }}
              @if($t->redmine_id === null)
                {{ Form::text('redmine_id', 'Sin numero de GLPI', ['class' => 'form-control-plaintext', 'readonly']) }}
              @else
                {{ Html::link('http://svn-server.mgc.es/redmine/issues/'.$t->redmine_id, $t->redmine_id, ['class' => 'btn btn-link', 'target' => '_blank']) }}
              @endif
            </div>
            <div class="">
              {{ Form::label('redmine_t', 'Tipo:') }}
              {{ Form::text('redmine_t', $t->redmine_t === '1' ? 'Tasca' : ($t->redmine_t === '2' ? 'Error' : 'No especificado' ), ['class' => 'form-control-plaintext', 'readonly']) }}
            </div>
          </p>
        </div>
        <div class="card-header">
          <h4 class="card-title"><span class="btn btn-secondary circle fa fa-database"></span> Repositori</h4>
          <h6 class="card-subtitle mb-2 text-muted"> </h6>
        </div>
        <div class="card-body">
          <p class="card-text">
            {{ $t->repo }}
          </p>
        </div>
          
        <div class="card-footer text-muted">
          @if($t->project_name != '' || $t->project_name != null)
                [Projecte: {{ $t->project_name }}]
          @endif
          @if($t->redmine_id === null && $t->glpi_id === null)
              Sin información
          @else
            @if($t->redmine_id !== null)
              @if($t->glpi_id !== null)
                @if($t->redmine_t !== '0')
                  {{ $t->redmine_t === '1' ? '[Tasca' : '[Error' }}:
                @else
                  [Redmine: 
                @endif
                #{{ $t->redmine_id }}][GLPI: #{{ $t->glpi_id }}]
              @else
                @if($t->redmine_t !== '0')
                  {{ $t->redmine_t === '1' ? '[Tasca' : '[Error' }}:
                @endif
                  {{ $t->redmine_id }}]
              @endif
            @else
              [GLPI: #{{ $t->glpi_id }}]
            @endif
          @endif
        </div>
      </div>
    </div>
  </div>

  <div class="col ml-auto">
    <div class="card">
      <div class="card-body">
        <h5>Información</h5>
        <ul class="nav flex-column text-left">
          <li class="nav-item">
            <span class="fa fa-calendar"></span> Creado
          </li>
          <li class="nav-item">
            {{ Date::parse($t->created_at)->format('d/m/Y') }}
            {{ Date::parse($t->created_at)->format('H:i') }}
          </li>
          <hr />
          <li class="nav-item">
            <span class="fa fa-calendar"></span> Modificado
          </li>
          <li class="nav-item">
            {{ Date::parse($t->updated_at)->format('d/m/Y') }}
            {{ Date::parse($t->updated_at)->format('H:i') }}
          </li>
        </ul>
      </div>
      <a href="{{ route('tareas.edit', $t->id) }}" class="btn btn-outline-primary btn-block"><span class="fa fa-pencil"></span> Editar</a>
    </div>
      
  </div>
</div>
@endsection